name: becoming-data-scientist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=19.3
  - jupyter=1.0
  - matplotlib=3.1
  - numpy=1.17
  - pandas=0.25
  - scipy=1.3
  - scikit-learn=0.21
  - seaborn=0.9
  - tensorflow=2.0
  - tabulate=0.8.3
  - importnb=0.6.0
  - pip:
      - sklearn-pandas